### ISSUE TITLE
文言の間違い

### ISSUE THREAD

**Issue by sawadatsuyoshi-mf** [cookpad/kuroko2#103]
https://github.com/cookpad/kuroko2/blob/b61d296229a8b0f0849aca5f3681e89867239d76/lib/autoload/kuroko2/workflow/notifier/concerns/chat_message_builder.rb#L16

にある英語の文言が間違っているので、Finished executingに直していただけると助かります。

**Comment by eisuke** [comment]
It has been fixed  https://github.com/cookpad/kuroko2/pull/104
