### ISSUE TITLE
How to kill working job that failed to start

### ISSUE THREAD

**Issue by tilfin** [cookpad/kuroko2#23]
At first, thank you for providing useful OSS!

We struggle with jobs that remain `working` status.
I guess there are jobs failed not to assign a worker of the executor.
They can not be operated at all on Web UI.
We want the way to force them to stop.

**Comment by eisuke** [comment]
1. Access your remain `working` "Job Instance Details" page ( `/definitions/:definition_id/instances/:instance_id` )
2. Press Backslash (\\) key.
3. The "Cancel" button turn into the "Force Cancel" button.
![force_cancel_button](https://cloud.githubusercontent.com/assets/39011/20511811/8d5dfba8-b0be-11e6-92d2-be850abb8440.png)
4. Press "Force Cancel" button.

This "Force Cancel" button updates the job instance status to cancel without checking the executor state.
I'm sorry It is undocumented feature.

**Comment by tilfin** [comment]
なんと！ありがとうございます。
