### ISSUE TITLE
read-only user

### ISSUE THREAD

**Issue by hatappi** [cookpad/kuroko2#31]
Hello.

I'm using kuroko2 with team.

The team has directors and engineers.
The engineer changes the setting of kuroko2, but the director only sees the execution situation.
Therefore, I want to make the director read-only.

However, current kuroko2 doesn't have authority management.

Is the function of authority management scheduled?

**Comment by eisuke** [comment]
@hatappi 

There is no plan to support authority management. Reasons are

* A user who is not the same team may operate jobs in our cases. (ie. SRE enginners)
* High cost to management authority for each user by admin.

If directors just grasp the job situation, How about using Email or Slack notification or Webhook?
Of course patches welcome (But I don't want to adopt full authority management. I welcome a different approach).

**Comment by hatappi** [comment]
@eisuke 
Thank you for reply.

I understood the reason.

For example, how about creating a plugin?
I'm thinking about creating a function that user make read only.

**Comment by eisuke** [comment]
Kuroko2 already supports extending application controller. (I'm sorry, it is not documented.)

* https://github.com/cookpad/kuroko2/blob/master/lib/kuroko2/engine.rb#L55
* https://github.com/cookpad/kuroko2/blob/master/spec/dummy/config/kuroko2.yml#L29
* https://github.com/cookpad/kuroko2/blob/master/spec/dummy/lib/dummy_extention.rb

You can add the callback method like that Read-Only user is allowed GET request only.
How about this way?

**Comment by hatappi** [comment]
It’s a great way.
I'll try.

Thank you so much.
