### ISSUE TITLE
[Q] Is there any API to kick a job? (or "incoming webhook")

### ISSUE THREAD

**Issue by gfx** [cookpad/kuroko2#48]
I'd like to kick, for example, deployment jobs from CI as a service.

Is there any API?

**Comment by eagletmt** [comment]
Yes. It should be documented though...
https://github.com/cookpad/kuroko2/blob/v0.3.4/spec/requests/api/job_instances_spec.rb

You need to check "Allow API execution of this job" at `/definitions/:job_definition_id/edit` page.

**Comment by sorah** [comment]
Yes we have. Unfortunately the current doc doesn't cover it...

Please read a code.

Also, note that we don't guarantee helpful support on GitHub issues.

**Comment by gfx** [comment]
Thanks!
