### ISSUE TITLE
[Q] How to restart command-executor processes during job execution.

### ISSUE THREAD

**Issue by takisawa** [cookpad/kuroko2#73]
## Overview

Could you tell me how to restart command-executor processes during job execution safety?

## Background

When I terminated a command-executor process with a following command for upgrade Kuroko2,
running `Working Jobs` had been left.

```
kill -QUIT `cat tmp/pids/command-executor.pid`
```

Then I deleted tha following DB data.
- kuroko2_job_instances: corresponding to the running `Working job`
- and corresponding to deleted kuroko2_job_instances
  - kuroko2_executions
  - kuroko2_logs
  - kuroko2_memory_consumption_logs
  - kuroko2_tokens

**Comment by eisuke** [comment]
@takisawa 
Please use the `TERM` signal, if you want to shutdown the command-excutor processes safety.
Check https://github.com/treasure-data/serverengine#signals for details.

**Comment by takisawa** [comment]
@eisuke 
Thank you very much for your support!
