### ISSUE TITLE
Is 'url' item in 'kuroko2.yml' no longer working as public URL?

### ISSUE THREAD

**Issue by corselia** [cookpad/kuroko2#81]
`Kuroko2` is very sexy product, thanks.

## not working?
btw, `url` item in `kuroko2.yml` is no longer working, is it?

for example, I defined `url` as `'http://foobar:12345'` and exec foreman as below.

```bash
$ foreman start
```

its log is here.

``` 
16:26:15 rails.1     | started with pid 28255
16:26:15 executor.1  | started with pid 28256
16:26:15 scheduler.1 | started with pid 28257
16:26:15 processor.1 | started with pid 28258
16:26:18 rails.1     | => Booting Puma
16:26:18 rails.1     | => Rails 5.1.3 application starting in development on http://localhost:5000
16:26:18 rails.1     | => Run `rails server -h` for more startup options
16:26:18 rails.1     | Puma starting in single mode...
16:26:18 rails.1     | * Version 3.9.1 (ruby 2.3.1-p112), codename: Private Caller
16:26:18 rails.1     | * Min threads: 5, max threads: 5
16:26:18 rails.1     | * Environment: development
16:26:18 rails.1     | * Listening on tcp://localhost:5000
16:26:18 rails.1     | Use Ctrl-C to stop
```

not updated 'url' :-(
the port number `5000` is defined in `engine.rb` at foreman gem.

## use '.env' to solve
if we wanna change url which is composed of host and port number, need to define in `.env` such as below.

```
HOST=example.com
PORT=12345
```

## use 'Procfile' to solve
or change `rails s` option in `Procfile` (below)

```
rails: ./bin/rails s -b example.com -p 12345
executor: ./bin/rails runner Kuroko2::Servers::CommandExecutor.new.run
scheduler: ./bin/rails runner Kuroko2::Servers::JobScheduler.new.run
processor: ./bin/rails runner Kuroko2::Servers::WorkflowProcessor.new.run
```

but this is NOT COOL, I consider.

## conclusion
if the above is right, it's better to add them to `Quick Start` in `docs/index.md`, isn't it?

Thank you.

## version
- kuroko2 (0.4.2)
- rails (5.1.3)
- ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by corselia** [comment]
oh, sorry! i wanna add one.

when I tried to notify to Slack, its link url contains `url` item. so issue title was wrong. as notify address, `url` item is available. 

therefore `Is 'url' item in 'kuroko2.yml' no longer working as public URL?` is correct :sob:
I modified.

**Comment by eisuke** [comment]
@corselia 

The `url` item uses only in the mail/slack notification templates.  It is not starting rails server configuration.

If you need using a different port number from `kuroko2.yml`'s default configuration, I recommend editing the `kuroko2.yml` directly or using '.env' solution.

I agree that the port number is different when using `foreman start` command along the Quick start, I fix it. Thank you for your reporting.

**Comment by corselia** [comment]
@eisuke 

I see. It is perfectly my misunderstanding, very sorry :cry: 
I have convinced `url` item is app url without doubt.
(because of [this article](http://dev.classmethod.jp/server-side/kuroko2/)...)

thank you for your response!
`Kuroko2` is very beauty product so I'm looking forward continuance development :smiley:
